"""add_accepted_declined_statuses

Revision ID: 92dc077db0b1
Revises: 81b21ffb0fb8
Create Date: 2026-02-24 21:30:14.535116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92dc077db0b1'
down_revision: Union[str, Sequence[str], None] = '81b21ffb0fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
